# Generated by Django 2.0.2 on 2019-04-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('pincode', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('alternate_email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('new_password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('pincode', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, choices=[('India', 'INDIA'), ('Other', 'OTHER')], max_length=128)),
                ('account_manager', models.CharField(blank=True, max_length=50)),
                ('select_group', models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('agriculture', 'AGRICULTURE'), ('consumer goods', 'CONSUMER GOODS'), ('stationary', 'STATIONARY'), ('electricals', 'ELECTRICALS')], max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('unique_code', models.CharField(max_length=10)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveIntegerField(default=1)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('accname', models.CharField(blank=True, max_length=50)),
                ('accno', models.CharField(blank=True, max_length=50)),
                ('ifc', models.CharField(blank=True, max_length=50)),
                ('bankname', models.CharField(blank=True, max_length=50)),
                ('acctype', models.CharField(blank=True, max_length=50)),
                ('refname', models.CharField(blank=True, max_length=50)),
                ('refphone', models.CharField(blank=True, max_length=50)),
                ('refdesignation', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
